### ISSUE TITLE
Replace while loops with recursion in tutorials

### ISSUE THREAD

**Issue by Aidenjn** [ChildsplayOSU/bogl-docs#29]
Remove uses of the while loop from any place it exists in the tutorial pages. In examples and exercises where the while loop is used, rewrite them to use recursion instead.

Do not delete the while loop tutorial, simply move it to the old_tutorials (located in the tutorials folder).

**Comment by garrettberliner** [comment]
Do you want me to also remove 'loop' from the glossary?

**Comment by garrettberliner** [comment]
Also, made all the changes. I have some questions that I will bring up in tomorrow's meeting, so I am waiting to push & make a pull request!

**Comment by Aidenjn** [comment]
Good work!
