### ISSUE TITLE
Board function examples

### ISSUE THREAD

**Issue by Aidenjn** [ChildsplayOSU/bogl-docs#30]
Add an example program for each built-in board function described in the board tutorial. These should be put in-between the function signature section and the exercise section for each function.

Feel free to borrow from the exercises for these. The exercises could probably use some improvement as well if you feel up to the task.

**Comment by jasonweber99** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Board Function Examples](https://trello.com/c/Pw0LAM4r/56-add-board-function-examples)

**Comment by jasonweber99** [comment]
Fixed with previous commit.
