### ISSUE TITLE
Documentation on how to run the project locally

### ISSUE THREAD

**Issue by Aidenjn** [ChildsplayOSU/bogl-docs#36]
We need instructions on how to install the needed tools and dependencies to run BoGL-Docs locally. Please address the following in the project's README.md:
- What to install and how to install it.
- How to run the project locally
This is so future people working on this project will have an easier time getting it running locally. For now you can just include instructions for Mac users (we'll write Windows instructions later).

**Comment by garrettberliner** [comment]
I have a rough draft of this locally that I will show you at the meeting on Tuesday.

**Comment by garrettberliner** [comment]
Published it into the readme
